FROM mysql:8.0

ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=1234
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=POSSGDB


CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]


 