name: Build Image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Image
        uses: docker/build-push-action@v4
        with:
          context: ./POSSG_BE
          file: ./POSSG_BE/Dockerfile
          platforms: linux/amd64
          push: true
          tags: possg/possg-be:latest

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          timeout: 40s
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull possg/possg-be:latest
            docker rm -f backend-test
            docker run \                            
              -p 3000:3000 \
              -e DB_HOST=db \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e NCS_ACCESSKEY=${{ secrets.NCS_ACCESSKEY }} \
              -e NCS_SECRETKEY=${{ secrets.NCS_SECRETKEY }} \
              -e NCS_SERVICEID=${{ secrets.NCS_SERVICEID }} \
              -e NCS_PHONE_NUMBER=${{ secrets.NCS_PHONE_NUMBER }} \
              -e JWT_TOKEN=${{ secrets.JWT_TOKEN }} \
              --link mariadb:db \
              possg/possg-be:latest
