name: Build Image

on:
  push:
    branches:
      - 'feature/cicd'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build Container Image
      uses: docker/build-push-action@v4
      with:
        context: ./POSSG_BE
        file: ./POSSG_BE/dockerfile
        platforms: linux/amd64
        push: true
        tags: possg/possg-be:latest
          